version: '3.8'

services:
  php:
    container_name: php-bot
    build: .
    volumes:
      - .:/var/www/html
      - ./data:/var/www/data
    depends_on:
      - mysql
    ports:
      - "8081:80"

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegram_bot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
      LANG: en_US.UTF-8
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
